#!/usr/bin/env python3
"""
Cursor rules adapter — generates .cursor/rules/*.mdc from the TR registry.

Exports the coding-relevant subset of registry/tr-registry.yaml as Cursor
project rules (MDC format: https://cursor.com/docs/context/rules), one file
per registry section. Safety-critical sections (secrets, data privacy, prompt
injection) are emitted with `alwaysApply: true`; every other section relies on
its `description` for agent-requested attachment. "Public Release" requirements
govern this repository's own release operations, not coding, and are excluded.

Generated files carry a provenance marker and must never be hand-edited —
rerun this script instead. `--check` verifies an existing output directory
matches what the registry would generate (changed, missing, or stale files
all count as drift), so CI can gate the committed example output.

The registry parser is stdlib-only by design (like every script in this repo)
and supports exactly the YAML subset the registry uses: a top-level
`requirements:` list whose items hold scalar fields and `>`-folded text
blocks. Anything else fails loudly with exit 2 — extend the parser
deliberately rather than letting it guess.

Usage:
    python3 scripts/cursor-rules-adapter.py [--registry PATH] [--out DIR] [--check]

Exit code 0 on successful generation or a clean --check, 1 when --check
finds drift, 2 on a usage error (missing or unparseable registry).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REGISTRY = REPO_ROOT / "registry" / "tr-registry.yaml"
DEFAULT_OUT = Path(".cursor") / "rules"

REQUIRED_FIELDS = ("id", "title", "status", "section", "text")

# Sections whose requirements govern this repo's release process rather than
# coding behavior — never exported as editor rules.
EXCLUDED_SECTIONS = {"Public Release"}

# Safety-critical sections are always in context; everything else attaches
# via its description (Cursor's "Apply Intelligently" type). "Agents" is in
# the set because it carries TR-SEC-003 (PII routes to local LLMs only).
ALWAYS_APPLY_SECTIONS = {"Secrets Management", "Data Privacy", "Prompt Injection", "Agents"}

# Statuses the registry is allowed to use; anything else is a typo until the
# registry (and this set) are extended deliberately.
ALLOWED_STATUSES = {"active", "retired", "deprecated"}

PROVENANCE = (
    "<!-- Generated by scripts/cursor-rules-adapter.py from "
    "registry/tr-registry.yaml. Do not edit by hand — regenerate instead. -->"
)


class RegistryParseError(Exception):
    """Registry file doesn't match the supported YAML subset."""


def _parse_scalar(value: str, lineno: int) -> str:
    """Unquote a scalar value; reject anything that would parse surprisingly."""
    if value[0] in ('"', "'"):
        if len(value) < 2 or not value.endswith(value[0]):
            raise RegistryParseError(
                f"line {lineno}: unterminated or trailing-content quoted value: {value!r}"
            )
        return value[1:-1]
    if value.startswith("#") or " #" in value or "\t#" in value:
        raise RegistryParseError(
            f"line {lineno}: inline comments in values are not supported: {value!r}"
        )
    return value


def parse_registry(text: str) -> list[dict[str, str]]:
    """Parse the deliberate YAML subset used by tr-registry.yaml.

    Supported: full-line comments, blank lines, a `requirements:` list whose
    items contain `key: scalar` fields and `key: >` folded blocks (continuation
    lines indented deeper than the key). Raises RegistryParseError otherwise.
    """
    requirements: list[dict[str, str]] = []
    seen_ids: set[str] = set()
    current: dict[str, str] | None = None
    folded_key: str | None = None
    folded_start = 0
    folded_lines: list[str] = []
    in_requirements = False

    def close_folded() -> None:
        nonlocal folded_key
        if folded_key is not None and current is not None:
            joined = " ".join(line.strip() for line in folded_lines if line.strip())
            if not joined:
                raise RegistryParseError(
                    f"line {folded_start}: folded block for {folded_key!r} is empty"
                )
            current[folded_key] = joined
            folded_key = None
            folded_lines.clear()

    def close_item(lineno: int) -> None:
        close_folded()
        if current is not None:
            missing = [f for f in REQUIRED_FIELDS if f not in current]
            if missing:
                raise RegistryParseError(
                    f"line {lineno}: requirement "
                    f"{current.get('id', '<no id>')!r} missing field(s): "
                    f"{', '.join(missing)}"
                )
            if current["status"] not in ALLOWED_STATUSES:
                raise RegistryParseError(
                    f"line {lineno}: requirement {current['id']!r} has unknown "
                    f"status {current['status']!r} (allowed: {', '.join(sorted(ALLOWED_STATUSES))})"
                )
            if current["id"] in seen_ids:
                raise RegistryParseError(
                    f"line {lineno}: duplicate requirement id {current['id']!r} "
                    "(IDs are permanent and unique — never reused)"
                )
            seen_ids.add(current["id"])
            requirements.append(current)

    for lineno, raw in enumerate(text.splitlines(), start=1):
        indent = len(raw) - len(raw.lstrip(" "))
        stripped = raw.strip()

        if folded_key is not None:
            if not stripped or indent >= 6:
                folded_lines.append(raw)
                continue
            close_folded()

        if not stripped or stripped.startswith("#"):
            continue

        if indent == 0:
            if stripped == "requirements:":
                in_requirements = True
                continue
            raise RegistryParseError(f"line {lineno}: unexpected top-level line: {stripped!r}")

        if not in_requirements:
            raise RegistryParseError(f"line {lineno}: content before 'requirements:' list")

        if indent == 2 and stripped.startswith("- "):
            close_item(lineno)
            current = {}
            stripped = stripped[2:].strip()
            # fall through to parse "id: ..." on the same line
        elif indent != 4:
            raise RegistryParseError(
                f"line {lineno}: unsupported indentation ({indent}) for: {stripped!r}"
            )

        if current is None:
            raise RegistryParseError(f"line {lineno}: field outside a list item")

        match = re.match(r"^([A-Za-z_][\w-]*):(?:\s+(.*))?$", stripped)
        if not match:
            raise RegistryParseError(f"line {lineno}: expected 'key: value', got: {stripped!r}")
        key, value = match.group(1), (match.group(2) or "").strip()

        if key in current:
            raise RegistryParseError(
                f"line {lineno}: duplicate field {key!r} within one requirement"
            )

        if value == ">":
            folded_key = key
            folded_start = lineno
        elif value:
            current[key] = _parse_scalar(value, lineno)
        else:
            raise RegistryParseError(
                f"line {lineno}: empty or nested value for {key!r} is unsupported"
            )

    close_item(len(text.splitlines()))
    if not requirements:
        raise RegistryParseError("no requirements found in registry")
    return requirements


def kebab(section: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", section.lower()).strip("-")


def select_subset(requirements: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    """Section -> requirements, registry order preserved, subset rules applied."""
    sections: dict[str, list[dict[str, str]]] = {}
    for req in requirements:
        if req["status"] != "active" or req["section"] in EXCLUDED_SECTIONS:
            continue
        sections.setdefault(req["section"], []).append(req)
    return sections


def render_section(section: str, reqs: list[dict[str, str]]) -> str:
    ids = ", ".join(r["id"] for r in reqs)
    always = "true" if section in ALWAYS_APPLY_SECTIONS else "false"
    parts = [
        "---",
        f'description: "LumiaForge AI engineering standards — {section} ({ids})"',
        f"alwaysApply: {always}",
        "---",
        "",
        PROVENANCE,
        "",
        f"# {section}",
    ]
    for req in reqs:
        parts.append("")
        parts.append(f"## {req['id']} — {req['title']}")
        parts.append("")
        parts.append(req["text"])
    return "\n".join(parts) + "\n"


def expected_files(registry_path: Path) -> dict[str, str]:
    text = registry_path.read_text(encoding="utf-8")
    sections = select_subset(parse_registry(text))
    if not sections:
        raise RegistryParseError(
            "registry has no exportable requirements (active, non-excluded sections)"
        )
    files: dict[str, str] = {}
    for name, reqs in sections.items():
        filename = f"{kebab(name)}.mdc"
        if filename in files:
            raise RegistryParseError(
                f"sections collide on output filename {filename!r} — rename one section"
            )
        files[filename] = render_section(name, reqs)
    return files


def check(out_dir: Path, expected: dict[str, str]) -> list[str]:
    """Return human-readable drift lines (empty = clean)."""
    drift: list[str] = []
    for name, content in expected.items():
        path = out_dir / name
        if not path.exists():
            drift.append(f"  MISSING  {path}")
        elif path.read_text(encoding="utf-8") != content:
            drift.append(f"  CHANGED  {path} (hand-edited or registry updated — regenerate)")
    expected_names = set(expected)
    for path in sorted(out_dir.glob("*.mdc")) if out_dir.is_dir() else []:
        if path.name not in expected_names:
            drift.append(f"  STALE    {path} (no matching registry section — delete or regenerate)")
    return drift


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--registry", default=str(DEFAULT_REGISTRY),
        help="Path to tr-registry.yaml (default: this repo's registry).",
    )
    parser.add_argument(
        "--out", default=str(DEFAULT_OUT),
        help="Output directory for .mdc files (default: .cursor/rules under the current directory).",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Verify --out matches what the registry generates; write nothing.",
    )
    args = parser.parse_args()

    registry_path = Path(args.registry)
    if not registry_path.is_file():
        print(f"Registry not found: {registry_path}", file=sys.stderr)
        return 2

    try:
        expected = expected_files(registry_path)
    except RegistryParseError as exc:
        print(f"Cannot parse registry ({registry_path}): {exc}", file=sys.stderr)
        return 2

    out_dir = Path(args.out)

    if args.check:
        drift = check(out_dir, expected)
        if drift:
            print(f"Cursor rules drift against {registry_path}:")
            print("\n".join(drift))
            print("\nRegenerate with: python3 scripts/cursor-rules-adapter.py "
                  f"--registry {registry_path} --out {out_dir}")
            return 1
        print(f"OK — {len(expected)} rule file(s) in {out_dir} match the registry.")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in expected.items():
        (out_dir / name).write_text(content, encoding="utf-8")
    print(f"Wrote {len(expected)} rule file(s) to {out_dir}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
