#!/usr/bin/env python3
"""
llms.txt generator — cross-tool discovery manifest generated from the TR registry.

Generalizes scripts/cursor-rules-adapter.py's "generate editor/agent context from
the registry" pattern (docs/agent-skills-integration.md, integration pattern 2) to
any agent framework, not just Cursor. Where the Cursor adapter emits tool-specific
.mdc files for a target repo, this emits a single llms.txt at this repo's own
root, following the llms.txt convention (https://llmstxt.org) — a plain markdown
index some agent/LLM tools already look for by default — listing this repo's own
registry, agent role specs, templates, and reference scripts.

Reuses cursor-rules-adapter.py's registry parser and coding-relevant subset
selection directly (dynamically loaded via importlib — the filename is hyphenated
and not import-able as a normal module) rather than re-implementing YAML parsing.

agents/, templates/, and scripts/ are read from this repo's own layout (not
CLI-configurable like --registry/--out) — unlike the Cursor adapter, which exports
into an arbitrary target repo, this file is inherently self-describing: it is
this repo's own manifest, not a template for someone else's.

Generated file carries a provenance marker and must never be hand-edited — rerun
this script instead. `--check` verifies llms.txt matches what the registry/
agents/templates/scripts would generate, so CI can gate the committed file.

Usage:
    python3 scripts/llms-txt-generator.py [--registry PATH] [--out FILE] [--check]

Exit code 0 on successful generation or a clean --check, 1 when --check finds
drift, 2 on a usage error (missing or unparseable registry).
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REGISTRY = REPO_ROOT / "registry" / "tr-registry.yaml"
DEFAULT_OUT = REPO_ROOT / "llms.txt"
AGENTS_DIR = REPO_ROOT / "agents"
TEMPLATES_DIR = REPO_ROOT / "templates"
SCRIPTS_DIR = REPO_ROOT / "scripts"

PROVENANCE = (
    "<!-- Generated by scripts/llms-txt-generator.py from registry/tr-registry.yaml, "
    "agents/, templates/, and scripts/. Do not edit by hand — regenerate instead. -->"
)

SUMMARY = (
    "An auditable engineering operating model for agent-assisted software work: a "
    "machine-readable requirement registry, portable agent role conventions, "
    "governance templates, and deterministic scripts — not a prompt library or a "
    "RAG platform."
)


def _load_cursor_adapter():
    """Dynamically load cursor-rules-adapter.py — its filename is hyphenated and
    not import-able as a normal Python module, so importlib loads it by path."""
    path = SCRIPTS_DIR / "cursor-rules-adapter.py"
    spec = importlib.util.spec_from_file_location("cursor_rules_adapter", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load {path}")
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        raise RuntimeError(f"failed to load {path}: {exc}") from exc
    return module


def _first_heading(path: Path) -> str:
    """Return the text of the first '# Heading' line in a markdown file, or its stem."""
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return path.stem


def _first_docstring_line(path: Path) -> str:
    """Return the first line of a Python file's module docstring, or "" if none
    or the file fails to parse (e.g. a WIP/scratch .py dropped in scripts/ with a
    syntax error) — degrades gracefully rather than crashing the whole manifest."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except SyntaxError:
        return ""
    doc = ast.get_docstring(tree)
    if not doc:
        return ""
    return doc.strip().splitlines()[0].strip()


def _registry_section(registry_path: Path, adapter) -> list[str]:
    text = registry_path.read_text(encoding="utf-8")
    sections = adapter.select_subset(adapter.parse_registry(text))
    if not sections:
        # Mirrors cursor-rules-adapter.py's expected_files() guard: fail loudly
        # rather than silently emitting a Registry section with no entries.
        raise adapter.RegistryParseError(
            "registry has no exportable requirements (active, non-excluded sections)"
        )
    lines = ["## Registry", "", "Machine-readable source: `registry/tr-registry.yaml`.", ""]
    for name, reqs in sections.items():
        lines.append(f"### {name}")
        lines.append("")
        for req in reqs:
            lines.append(f"- **{req['id']}** — {req['title']}: {req['text']}")
        lines.append("")
    return lines


def _dir_section(title: str, dir_path: Path, blurb: str) -> list[str]:
    lines = [f"## {title}", "", blurb, ""]
    # sorted() is required for determinism (test_output_is_deterministic) —
    # Path.glob() order is filesystem-dependent, not guaranteed stable.
    for path in sorted(dir_path.glob("*.md")):
        rel = path.relative_to(REPO_ROOT)
        lines.append(f"- [{rel}]({rel}) — {_first_heading(path)}")
    lines.append("")
    return lines


def _scripts_section() -> list[str]:
    lines = ["## Scripts", "", "Deterministic reference scripts (stdlib-only).", ""]
    # sorted() is required for determinism — see _dir_section.
    for path in sorted(SCRIPTS_DIR.glob("*.py")):
        rel = path.relative_to(REPO_ROOT)
        doc = _first_docstring_line(path)
        lines.append(f"- [{rel}]({rel})" + (f" — {doc}" if doc else ""))
    lines.append("")
    return lines


def generate(registry_path: Path, adapter) -> str:
    lines = [
        "# LumiaForge AI Engineering Standards",
        "",
        SUMMARY,
        "",
        PROVENANCE,
        "",
    ]
    lines += _registry_section(registry_path, adapter)
    lines += _dir_section(
        "Agent Roles", AGENTS_DIR,
        "Tool-neutral role specs for developer, reviewer, private researcher, and public researcher agents.",
    )
    lines += _dir_section(
        "Templates", TEMPLATES_DIR,
        "Governance and eval templates: ADR, impact assessment, maturity checklist, completion checklist, LLM eval.",
    )
    lines += _scripts_section()
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--registry", default=str(DEFAULT_REGISTRY),
        help="Path to tr-registry.yaml (default: this repo's registry).",
    )
    parser.add_argument(
        "--out", default=str(DEFAULT_OUT),
        help="Output path for llms.txt (default: this repo's root).",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Verify --out matches what the sources would generate; write nothing.",
    )
    args = parser.parse_args()

    registry_path = Path(args.registry)
    if not registry_path.is_file():
        print(f"Registry not found: {registry_path}", file=sys.stderr)
        return 2

    adapter = _load_cursor_adapter()
    try:
        content = generate(registry_path, adapter)
    except adapter.RegistryParseError as exc:
        print(f"Cannot parse registry ({registry_path}): {exc}", file=sys.stderr)
        return 2

    out_path = Path(args.out)

    if args.check:
        # Unlike cursor-rules-adapter.py's check() (which manages a whole directory
        # of .mdc files and also flags STALE extras), this script manages exactly
        # one file at a fixed path — there is no "stale extra file" case to detect.
        if not out_path.exists():
            print(f"MISSING {out_path}", file=sys.stderr)
            return 1
        if out_path.read_text(encoding="utf-8") != content:
            print(f"CHANGED {out_path} (hand-edited or source updated — regenerate)", file=sys.stderr)
            return 1
        print(f"OK — {out_path} matches the registry/agents/templates/scripts.")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
